name: develop deployment
on: [push]
jobs:
  test-deploy-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Download codeclimate test reporter tool
        run: |
          curl -fL https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ${GITHUB_WORKSPACE}/cc-test-reporter
          chmod +x ${GITHUB_WORKSPACE}/cc-test-reporter
      - name: Call codeclimate before build
        run: ${GITHUB_WORKSPACE}/cc-test-reporter before-build --id ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run e2e
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
      - name: publish code coverage
        run: ${GITHUB_WORKSPACE}/cc-test-reporter after-build --id ${{ secrets.CC_TEST_REPORTER_ID }}