name: develop deployment
on: [push]
jobs:
  test-deploy-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run e2e
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
      - name: publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: fe6e43fa305179b23ece798af734101670f8c4394ab78b5ff410e523e4967b63
