name: develop deployment
on: [push]
jobs:
  test-deploy-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup test reporter ID
        run: |
          echo "CC_TEST_REPORTER_ID=${{ secrets.CC_TEST_REPORTER_ID }}" >> $GITHUB_ENV
      - name: Download codeclimate test reporter tool
        run: |
          curl "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64" -o "cc-test-reporter"
          chmod 744 ./cc-test-reporter
      - name: Call codeclimate before build
        run: ./cc-test-reporter before-build
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run e2e
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
      - name: publish code coverage
        run: ./cc-test-reporter after-build
